import type { LocaleKeys } from "../locales/locales";
import type {
  TElementType,
  TRarity,
  TWaifu,
  TDropItem,
  TInventoryItem,
  TLocation,
  ILocationConfig,
  IGlobalUpgrades,
  TLocationProgress,
  TInventoryItemId,
} from "../types";

export const BASE_DROP_RATES: Record<TRarity, number> = {
  common: 0.6,
  uncommon: 0.25,
  rare: 0.1,
  epic: 0.04,
  legendary: 0.01,
  mythic: 0.001,
};

export const ELEMENT_COLORS: Record<TElementType, string> = {
  water: "#2196f3",
  fire: "#f44336",
  earth: "#4caf50",
  ice: "#00bcd4",
  light: "#ffeb3b",
  dark: "#9c27b0",
  physical: "#9e9e9e",
};

export const RARITY_COLORS: Record<TRarity, string> = {
  common: "#9e9e9e",
  uncommon: "#4caf50",
  rare: "#2196f3",
  epic: "#9c27b0",
  legendary: "#ff9800",
  mythic: "#f44336",
};

export const RARITY_KEYS: Record<TRarity, string> = {
  common: "common",
  uncommon: "uncommon",
  rare: "rare",
  epic: "epic",
  legendary: "legendary",
  mythic: "mythic",
};

export const ELEMENT_KEYS: Record<TElementType, string> = {
  water: "water",
  fire: "fire",
  earth: "earth",
  ice: "ice",
  light: "light",
  dark: "dark",
  physical: "physical",
};

export const INVENTORY_ITEMS: Record<TInventoryItemId, Omit<TInventoryItem, "count">> = {
  gem: {
    id: "gem",
    nameKey: "gem",
    descriptionKey: "items.gem.desc",
    icon: "gem",
    rarity: "common",
    type: "currency",
    maxStack: 999999999,
    canCraft: true,
    ingredients: [
      { itemId: "coin", count: 1 },
      { itemId: "essence", count: 1 },
    ],
  },
  essence: {
    id: "essence",
    nameKey: "essence",
    descriptionKey: "items.essence.desc",
    icon: "essence",
    rarity: "common",
    type: "currency",
    maxStack: 999999999,
    canCraft: true,

    ingredients: [
      { itemId: "coin", count: 5 },
      { itemId: "gem", count: 100 },
    ],
  },
  coin: {
    id: "coin",
    nameKey: "coin",
    descriptionKey: "items.coin.desc",
    icon: "coin",
    rarity: "common",
    type: "currency",
    maxStack: 999999999,
  },
  gel: {
    id: "gel",
    nameKey: "gel",
    descriptionKey: "items.gel.desc",
    icon: "gel",
    rarity: "common",
    type: "material",
    maxStack: 200,
  },
  slime_core: {
    id: "slime_core",
    nameKey: "slimeCore",
    descriptionKey: "items.slimeCore.desc",
    icon: "slime_core",
    rarity: "rare",
    type: "collection",
    maxStack: 1,
  },
  goblin_dagger: {
    id: "goblin_dagger",
    nameKey: "goblinDagger",
    descriptionKey: "items.goblinDagger.desc",
    icon: "dagger",
    rarity: "uncommon",
    type: "collection",
    maxStack: 1,
  },
  goblin_ear: {
    id: "goblin_ear",
    nameKey: "goblinEar",
    descriptionKey: "items.goblinEar.desc",
    icon: "ear",
    rarity: "common",
    type: "material",
    maxStack: 200,
  },
  bone: {
    id: "bone",
    nameKey: "bone",
    descriptionKey: "items.bone.desc",
    icon: "bone",
    rarity: "common",
    type: "material",
    maxStack: 200,
  },
  skull: {
    id: "skull",
    nameKey: "skull",
    descriptionKey: "items.skull.desc",
    icon: "skull",
    rarity: "uncommon",
    type: "collection",
    maxStack: 1,
  },
  ectoplasm: {
    id: "ectoplasm",
    nameKey: "ectoplasm",
    descriptionKey: "items.ectoplasm.desc",
    icon: "ectoplasm",
    rarity: "uncommon",
    type: "material",
    maxStack: 200,
  },
  soul_shard: {
    id: "soul_shard",
    nameKey: "soulShard",
    descriptionKey: "items.soulShard.desc",
    icon: "soul_shard",
    rarity: "rare",
    type: "collection",
    maxStack: 1,
  },
  magic_scroll: {
    id: "magic_scroll",
    nameKey: "magicScroll",
    descriptionKey: "items.magicScroll.desc",
    icon: "scroll",
    rarity: "rare",
    type: "material",
    maxStack: 200,
  },
  dark_orb: {
    id: "dark_orb",
    nameKey: "darkOrb",
    descriptionKey: "items.darkOrb.desc",
    icon: "orb_dark",
    rarity: "epic",
    type: "collection",
    maxStack: 1,
  },
  mage_staff: {
    id: "mage_staff",
    nameKey: "mageStaff",
    descriptionKey: "items.mageStaff.desc",
    icon: "staff",
    rarity: "legendary",
    type: "collection",
    maxStack: 1,
  },
  demon_horn: {
    id: "demon_horn",
    nameKey: "demonHorn",
    descriptionKey: "items.demonHorn.desc",
    icon: "horn",
    rarity: "rare",
    type: "material",
    maxStack: 200,
  },
  hellfire_essence: {
    id: "hellfire_essence",
    nameKey: "hellfireEssence",
    descriptionKey: "items.hellfireEssence.desc",
    icon: "essence_fire",
    rarity: "epic",
    type: "collection",
    maxStack: 1,
  },
  demon_wing: {
    id: "demon_wing",
    nameKey: "demonWing",
    descriptionKey: "items.demonWing.desc",
    icon: "wing",
    rarity: "legendary",
    type: "collection",
    maxStack: 1,
  },
  ancient_coin: {
    id: "ancient_coin",
    nameKey: "ancientCoin",
    descriptionKey: "items.ancientCoin.desc",
    icon: "coin_old",
    rarity: "uncommon",
    type: "collection",
    maxStack: 1,
    collectionCategory: "accessory",
  },

  forest_essence: {
    id: "forest_essence",
    nameKey: "forestEssence",
    descriptionKey: "items.forestEssence.desc",
    icon: "forest_essence",
    rarity: "common",
    type: "material",
    maxStack: 200,
  },
  spider_venom: {
    id: "spider_venom",
    nameKey: "spiderVenom",
    descriptionKey: "items.spiderVenom.desc",
    icon: "spider_venom",
    rarity: "uncommon",
    type: "material",
    maxStack: 200,
  },

  sand_stone: {
    id: "sand_stone",
    nameKey: "sandStone",
    descriptionKey: "items.sandStone.desc",
    icon: "sand_stone",
    rarity: "common",
    type: "material",
    maxStack: 200,
  },

  ice_crystal: {
    id: "ice_crystal",
    nameKey: "iceCrystal",
    descriptionKey: "items.iceCrystal.desc",
    icon: "ice_crystal",
    rarity: "common",
    type: "material",
    maxStack: 200,
  },
  frost_fang: {
    id: "frost_fang",
    nameKey: "frostFang",
    descriptionKey: "items.frostFang.desc",
    icon: "frost_fang",
    rarity: "uncommon",
    type: "material",
    maxStack: 200,
  },
  lava_chunk: {
    id: "lava_chunk",
    nameKey: "lavaChunk",
    descriptionKey: "items.lavaChunk.desc",
    icon: "lava_chunk",
    rarity: "common",
    type: "material",
    maxStack: 200,
  },
  imp_ash: {
    id: "imp_ash",
    nameKey: "impAsh",
    descriptionKey: "items.impAsh.desc",
    icon: "imp_ash",
    rarity: "common",
    type: "material",
    maxStack: 200,
  },

  cursed_cloth: {
    id: "cursed_cloth",
    nameKey: "cursedCloth",
    descriptionKey: "items.cursedCloth.desc",
    icon: "cursed_cloth",
    rarity: "uncommon",
    type: "material",
    maxStack: 200,
  },
  void_essence: {
    id: "void_essence",
    nameKey: "voidEssence",
    descriptionKey: "items.voidEssence.desc",
    icon: "void_essence",
    rarity: "rare",
    type: "material",
    maxStack: 200,
  },

  affection_potion_forest: {
    id: "affection_potion_forest",
    nameKey: "affectionPotionForest",
    descriptionKey: "items.affectionPotionForest.desc",
    icon: "potion_forest",
    rarity: "common",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "forest_essence", count: 3 },
      { itemId: "spider_venom", count: 2 },
    ],
    effect: { type: "affection", value: 10, target: "selected_waifu" },
  },
  exp_scroll_forest: {
    id: "exp_scroll_forest",
    nameKey: "expScrollForest",
    descriptionKey: "items.expScrollForest.desc",
    icon: "scroll_forest_exp",
    rarity: "common",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "gel", count: 4 },
      { itemId: "forest_essence", count: 2 },
      { itemId: "essence", count: 3 },
    ],
    effect: { type: "exp", value: 500, target: "selected_waifu" },
  },
  level_down_scroll_forest: {
    id: "level_down_scroll_forest",
    nameKey: "levelDownScrollForest",
    descriptionKey: "items.levelDownScrollForest.desc",
    icon: "scroll_forest_down",
    rarity: "common",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [{ itemId: "essence", count: 3 }],
    effect: { type: "level_down", value: 5, target: "current_location" },
  },

  affection_potion_desert: {
    id: "affection_potion_desert",
    nameKey: "affectionPotionDesert",
    descriptionKey: "items.affectionPotionDesert.desc",
    icon: "potion_desert",
    rarity: "uncommon",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "sand_stone", count: 4 },
      { itemId: "ectoplasm", count: 2 },
    ],
    effect: { type: "affection", value: 100, target: "selected_waifu" },
  },
  exp_scroll_desert: {
    id: "exp_scroll_desert",
    nameKey: "expScrollDesert",
    descriptionKey: "items.expScrollDesert.desc",
    icon: "scroll_desert_exp",
    rarity: "uncommon",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "sand_stone", count: 3 },
      { itemId: "ectoplasm", count: 3 },
      { itemId: "essence", count: 5 },
    ],
    effect: { type: "exp", value: 3000, target: "selected_waifu" },
  },
  level_down_scroll_desert: {
    id: "level_down_scroll_desert",
    nameKey: "levelDownScrollDesert",
    descriptionKey: "items.levelDownScrollDesert.desc",
    icon: "scroll_desert_down",
    rarity: "uncommon",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "sand_stone", count: 6 },
      { itemId: "ectoplasm", count: 4 },
    ],
    effect: { type: "level_down", value: 10, target: "current_location" },
  },

  affection_potion_ice: {
    id: "affection_potion_ice",
    nameKey: "affectionPotionIce",
    descriptionKey: "items.affectionPotionIce.desc",
    icon: "potion_ice",
    rarity: "rare",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "ice_crystal", count: 3 },
      { itemId: "frost_fang", count: 2 },
    ],
    effect: { type: "affection", value: 200, target: "selected_waifu" },
  },
  exp_scroll_ice: {
    id: "exp_scroll_ice",
    nameKey: "expScrollIce",
    descriptionKey: "items.expScrollIce.desc",
    icon: "scroll_ice_exp",
    rarity: "rare",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "ice_crystal", count: 4 },
      { itemId: "frost_fang", count: 2 },
      { itemId: "bone", count: 3 },
      { itemId: "essence", count: 8 },
    ],
    effect: { type: "exp", value: 10000, target: "selected_waifu" },
  },
  level_down_scroll_ice: {
    id: "level_down_scroll_ice",
    nameKey: "levelDownScrollIce",
    descriptionKey: "items.levelDownScrollIce.desc",
    icon: "scroll_ice_down",
    rarity: "rare",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "frost_fang", count: 4 },
      { itemId: "ice_crystal", count: 2 },
    ],
    effect: { type: "level_down", value: 15, target: "current_location" },
  },

  affection_potion_volcano: {
    id: "affection_potion_volcano",
    nameKey: "affectionPotionVolcano",
    descriptionKey: "items.affectionPotionVolcano.desc",
    icon: "potion_volcano",
    rarity: "epic",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "imp_ash", count: 3 },
      { itemId: "lava_chunk", count: 2 },
    ],
    effect: { type: "affection", value: 666, target: "selected_waifu" },
  },
  exp_scroll_volcano: {
    id: "exp_scroll_volcano",
    nameKey: "expScrollVolcano",
    descriptionKey: "items.expScrollVolcano.desc",
    icon: "scroll_volcano_exp",
    rarity: "epic",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "imp_ash", count: 4 },
      { itemId: "lava_chunk", count: 3 },
      { itemId: "demon_horn", count: 1 },
      { itemId: "essence", count: 10 },
    ],
    effect: { type: "exp", value: 20000, target: "selected_waifu" },
  },
  level_down_scroll_volcano: {
    id: "level_down_scroll_volcano",
    nameKey: "levelDownScrollVolcano",
    descriptionKey: "items.levelDownScrollVolcano.desc",
    icon: "scroll_volcano_down",
    rarity: "epic",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "lava_chunk", count: 5 },
      { itemId: "imp_ash", count: 3 },
    ],
    effect: { type: "level_down", value: 20, target: "current_location" },
  },

  affection_potion_castle: {
    id: "affection_potion_castle",
    nameKey: "affectionPotionCastle",
    descriptionKey: "items.affectionPotionCastle.desc",
    icon: "potion_castle",
    rarity: "legendary",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "cursed_cloth", count: 3 },
      { itemId: "ectoplasm", count: 3 },
    ],
    effect: { type: "affection", value: 1200, target: "selected_waifu" },
  },
  exp_scroll_castle: {
    id: "exp_scroll_castle",
    nameKey: "expScrollCastle",
    descriptionKey: "items.expScrollCastle.desc",
    icon: "scroll_castle_exp",
    rarity: "legendary",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "cursed_cloth", count: 4 },
      { itemId: "bone", count: 5 },
      { itemId: "essence", count: 15 },
    ],
    effect: { type: "exp", value: 40000, target: "selected_waifu" },
  },
  level_down_scroll_castle: {
    id: "level_down_scroll_castle",
    nameKey: "levelDownScrollCastle",
    descriptionKey: "items.levelDownScrollCastle.desc",
    icon: "scroll_castle_down",
    rarity: "legendary",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "cursed_cloth", count: 5 },
      { itemId: "ectoplasm", count: 4 },
    ],
    effect: { type: "level_down", value: 30, target: "current_location" },
  },

  affection_potion_abyss: {
    id: "affection_potion_abyss",
    nameKey: "affectionPotionAbyss",
    descriptionKey: "items.affectionPotionAbyss.desc",
    icon: "potion_abyss",
    rarity: "mythic",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "void_essence", count: 2 },
      { itemId: "ectoplasm", count: 4 },
    ],
    effect: { type: "affection", value: 3000, target: "selected_waifu" },
  },
  exp_scroll_abyss: {
    id: "exp_scroll_abyss",
    nameKey: "expScrollAbyss",
    descriptionKey: "items.expScrollAbyss.desc",
    icon: "scroll_abyss_exp",
    rarity: "mythic",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "void_essence", count: 3 },
      { itemId: "ectoplasm", count: 5 },
      { itemId: "essence", count: 20 },
    ],
    effect: { type: "exp", value: 80000, target: "selected_waifu" },
  },
  level_down_scroll_abyss: {
    id: "level_down_scroll_abyss",
    nameKey: "levelDownScrollAbyss",
    descriptionKey: "items.levelDownScrollAbyss.desc",
    icon: "scroll_abyss_down",
    rarity: "mythic",
    type: "consumable",
    maxStack: 99,
    canCraft: true,
    ingredients: [
      { itemId: "void_essence", count: 4 },
      { itemId: "ectoplasm", count: 3 },
    ],
    effect: { type: "level_down", value: 50, target: "current_location" },
  },
};

export const testWaifus: TWaifu[] = [
  {
    id: "wf_tiamat_001",
    nameKey: "Tiamat",
    rarity: "mythic",
    element: "water",
    image: "/assets/images/waifus/Tiamat.png",
    description: "waifus.Tiamat.desc",
    clickPower: 1000,
    critChance: 0.15,
    critMultiplier: 3.0,
  },
  {
    id: "wf_cerberus_001",
    nameKey: "Cerberus",
    rarity: "legendary",
    element: "dark",
    image: "/assets/images/waifus/Cerberus.png",
    description: "waifus.Cerberus.desc",
    clickPower: 800,
    critChance: 0.12,
    critMultiplier: 2.8,
  },
  {
    id: "wf_phoenix_001",
    nameKey: "Phoenix",
    rarity: "legendary",
    element: "fire",
    image: "/assets/images/waifus/Phoenix.png",
    description: "waifus.Phoenix.desc",
    clickPower: 750,
    critChance: 0.12,
    critMultiplier: 2.5,
  },
  {
    id: "wf_leviathan_001",
    nameKey: "Leviathan",
    rarity: "epic",
    element: "water",
    image: "/assets/images/waifus/Leviathan.png",
    description: "waifus.Leviathan.desc",
    clickPower: 500,
    critChance: 0.1,
    critMultiplier: 2.2,
  },
  {
    id: "wf_terra_001",
    nameKey: "Terra",
    rarity: "epic",
    element: "earth",
    image: "/assets/images/waifus/Terra.png",
    description: "waifus.Terra.desc",
    clickPower: 480,
    critChance: 0.08,
    critMultiplier: 2.5,
  },
  {
    id: "wf_yuki_001",
    nameKey: "YukiOnna",
    rarity: "epic",
    element: "ice",
    image: "/assets/images/waifus/YukiOnna.png",
    description: "waifus.YukiOnna.desc",
    clickPower: 490,
    critChance: 0.1,
    critMultiplier: 2.3,
  },
  {
    id: "wf_ignis_001",
    nameKey: "Ignis",
    rarity: "rare",
    element: "fire",
    image: "/assets/images/waifus/Ignis.png",
    description: "waifus.Ignis.desc",
    clickPower: 300,
    critChance: 0.08,
    critMultiplier: 2.0,
  },
  {
    id: "wf_aqua_001",
    nameKey: "Aqua",
    rarity: "rare",
    element: "water",
    image: "/assets/images/waifus/Aqua.png",
    description: "waifus.Aqua.desc",
    clickPower: 290,
    critChance: 0.08,
    critMultiplier: 2.0,
  },
  {
    id: "wf_gaia_001",
    nameKey: "Gaia",
    rarity: "rare",
    element: "earth",
    image: "/assets/images/waifus/Gaia.png",
    description: "waifus.Gaia.desc",
    clickPower: 310,
    critChance: 0.06,
    critMultiplier: 2.2,
  },
  {
    id: "wf_umbra_001",
    nameKey: "Umbra",
    rarity: "rare",
    element: "dark",
    image: "/assets/images/waifus/Umbra.png",
    description: "waifus.Umbra.desc",
    clickPower: 320,
    critChance: 0.1,
    critMultiplier: 2.0,
  },
  {
    id: "wf_ruby_001",
    nameKey: "Ruby",
    rarity: "uncommon",
    element: "fire",
    image: "/assets/images/waifus/Ruby.png",
    description: "waifus.Ruby.desc",
    clickPower: 160,
    critChance: 0.06,
    critMultiplier: 1.8,
  },
  {
    id: "wf_sapphire_001",
    nameKey: "Sapphire",
    rarity: "uncommon",
    element: "water",
    image: "/assets/images/waifus/Sapphire.png",
    description: "waifus.Sapphire.desc",
    clickPower: 150,
    critChance: 0.06,
    critMultiplier: 1.8,
  },
  {
    id: "wf_emerald_001",
    nameKey: "Emerald",
    rarity: "uncommon",
    element: "earth",
    image: "/assets/images/waifus/Emerald.png",
    description: "waifus.Emerald.desc",
    clickPower: 165,
    critChance: 0.05,
    critMultiplier: 2.0,
  },
  {
    id: "wf_frost_001",
    nameKey: "Frost",
    rarity: "uncommon",
    element: "ice",
    image: "/assets/images/waifus/Frost.png",
    description: "waifus.Frost.desc",
    clickPower: 155,
    critChance: 0.07,
    critMultiplier: 1.9,
  },
  {
    id: "wf_lux_001",
    nameKey: "Lux",
    rarity: "uncommon",
    element: "light",
    image: "/assets/images/waifus/Lux.png",
    description: "waifus.Lux.desc",
    clickPower: 145,
    critChance: 0.08,
    critMultiplier: 1.7,
  },
  {
    id: "wf_sakura_001",
    nameKey: "Sakura",
    rarity: "common",
    element: "physical",
    image: "/assets/images/waifus/Sakura.png",
    description: "waifus.Sakura.desc",
    clickPower: 100,
    critChance: 0.05,
    critMultiplier: 1.5,
  },
  {
    id: "wf_yui_001",
    nameKey: "Yui",
    rarity: "common",
    element: "physical",
    image: "/assets/images/waifus/Yui.png",
    description: "waifus.Yui.desc",
    clickPower: 90,
    critChance: 0.04,
    critMultiplier: 1.5,
  },
  {
    id: "wf_hana_001",
    nameKey: "Hana",
    rarity: "common",
    element: "water",
    image: "/assets/images/waifus/Hana.png",
    description: "waifus.Hana.desc",
    clickPower: 85,
    critChance: 0.05,
    critMultiplier: 1.4,
  },
  {
    id: "wf_momo_001",
    nameKey: "Momo",
    rarity: "common",
    element: "fire",
    image: "/assets/images/waifus/Momo.png",
    description: "waifus.Momo.desc",
    clickPower: 88,
    critChance: 0.05,
    critMultiplier: 1.5,
  },
  {
    id: "wf_rin_001",
    nameKey: "Rin",
    rarity: "common",
    element: "earth",
    image: "/assets/images/waifus/Rin.png",
    description: "waifus.Rin.desc",
    clickPower: 82,
    critChance: 0.04,
    critMultiplier: 1.6,
  },
  {
    id: "wf_sora_001",
    nameKey: "Sora",
    rarity: "common",
    element: "physical",
    image: "/assets/images/waifus/Sora.png",
    description: "waifus.Sora.desc",
    clickPower: 86,
    critChance: 0.06,
    critMultiplier: 1.4,
  },
];

export interface MonsterTemplate {
  id: string;
  nameKey: string;
  baseHp: number;
  sprite: string;
  resistances: Partial<Record<TElementType, number>>;
  isBoss: boolean;
  description: LocaleKeys;
  drops: TDropItem[];
}

export const MONSTER_TEMPLATES: MonsterTemplate[] = [
  // ========== FOREST ==========
  {
    id: "slime",
    nameKey: "slime",
    baseHp: 100,
    sprite: "/assets/images/enemies/Slime.png",
    resistances: { water: -0.3, fire: 0.2 },
    isBoss: false,
    description: "monsters.slime.desc",
    drops: [
      { id: "gel", nameKey: "gel", chance: 0.5, minCount: 1, maxCount: 3, type: "material" },
      { id: "slime_core", nameKey: "slimeCore", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
  {
    id: "goblin",
    nameKey: "goblin",
    baseHp: 120,
    sprite: "/assets/images/enemies/Goblin.png",
    resistances: { physical: -0.2, fire: 0.1 },
    isBoss: false,
    description: "monsters.goblin.desc",
    drops: [
      { id: "goblin_dagger", nameKey: "goblinDagger", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
      { id: "goblin_ear", nameKey: "goblinEar", chance: 0.4, minCount: 1, maxCount: 2, type: "material" },
    ],
  },
  {
    id: "direWolf",
    nameKey: "direWolf",
    baseHp: 130,
    sprite: "/assets/images/enemies/DireWolf.png",
    resistances: { fire: -0.2, ice: 0.2 },
    isBoss: false,
    description: "monsters.direWolf.desc",
    drops: [{ id: "bone", nameKey: "bone", chance: 0.5, minCount: 2, maxCount: 4, type: "material" }],
  },
  {
    id: "forest_golem",
    nameKey: "forestGolem",
    baseHp: 200,
    sprite: "/assets/images/enemies/ForestGolem.png",
    resistances: { earth: 0.3, fire: -0.4, physical: 0.2 },
    isBoss: false,
    description: "monsters.forestGolem.desc",
    drops: [
      { id: "bone", nameKey: "bone", chance: 0.4, minCount: 1, maxCount: 3, type: "material" },
      { id: "forest_essence", nameKey: "forestEssence", chance: 0.1, minCount: 1, maxCount: 2, type: "material" },
    ],
  },
  {
    id: "poison_spider",
    nameKey: "poisonSpider",
    baseHp: 110,
    sprite: "/assets/images/enemies/PoisonSpider.png",
    resistances: { earth: 0.2, fire: -0.3, ice: 0.1 },
    isBoss: false,
    description: "monsters.poisonSpider.desc",
    drops: [
      { id: "ectoplasm", nameKey: "ectoplasm", chance: 0.3, minCount: 1, maxCount: 2, type: "material" },
      { id: "gel", nameKey: "gel", chance: 0.5, minCount: 1, maxCount: 3, type: "material" },
      { id: "spider_venom", nameKey: "spiderVenom", chance: 0.15, minCount: 1, maxCount: 1, type: "material" },
    ],
  },
  {
    id: "forest_guardian",
    nameKey: "forestGuardian",
    baseHp: 500,
    sprite: "/assets/images/enemies/ForestGuardian.png",
    resistances: { earth: 0.5, fire: -0.5, light: 0.2, physical: 0.3 },
    isBoss: true,
    description: "monsters.forestGuardian.desc",
    drops: [{ id: "magic_scroll", nameKey: "magicScroll", chance: 0.5, minCount: 1, maxCount: 2, type: "material" }],
  },

  {
    id: "mummy",
    nameKey: "mummy",
    baseHp: 140,
    sprite: "/assets/images/enemies/Mummy.png",
    resistances: { fire: 0.3, ice: -0.4, earth: 0.2 },
    isBoss: false,
    description: "monsters.mummy.desc",
    drops: [
      { id: "ancient_coin", nameKey: "ancientCoin", chance: 0.002, minCount: 1, maxCount: 2, type: "collection" },
    ],
  },
  {
    id: "mimic",
    nameKey: "mimic",
    baseHp: 160,
    sprite: "/assets/images/enemies/Mimic.png",
    resistances: { physical: -0.3, fire: 0.2, earth: 0.1 },
    isBoss: false,
    description: "monsters.mimic.desc",
    drops: [{ id: "coin", nameKey: "coin", chance: 0.8, minCount: 10, maxCount: 30, type: "currency" }],
  },
  {
    id: "sand_worm",
    nameKey: "sandWorm",
    baseHp: 180,
    sprite: "/assets/images/enemies/SandWorm.png",
    resistances: { earth: 0.4, ice: -0.5, fire: 0.3 },
    isBoss: false,
    description: "monsters.sandWorm.desc",
    drops: [
      { id: "bone", nameKey: "bone", chance: 0.5, minCount: 2, maxCount: 4, type: "material" },
      { id: "ancient_coin", nameKey: "ancientCoin", chance: 0.002, minCount: 1, maxCount: 2, type: "collection" },
      { id: "sand_stone", nameKey: "sandStone", chance: 0.3, minCount: 1, maxCount: 3, type: "material" },
    ],
  },
  {
    id: "scarab_beetle",
    nameKey: "scarabBeetle",
    baseHp: 140,
    sprite: "/assets/images/enemies/ScarabBeetle.png",
    resistances: { light: 0.3, physical: 0.2, fire: 0.2, earth: -0.2 },
    isBoss: false,
    description: "monsters.scarabBeetle.desc",
    drops: [
      { id: "ectoplasm", nameKey: "ectoplasm", chance: 0.25, minCount: 1, maxCount: 2, type: "material" },
      { id: "soul_shard", nameKey: "soulShard", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
  {
    id: "desert_colossus",
    nameKey: "desertColossus",
    baseHp: 550,
    sprite: "/assets/images/enemies/DesertColossus.png",
    resistances: { earth: 0.5, ice: -0.5, fire: 0.4, physical: 0.2 },
    isBoss: true,
    description: "monsters.desertColossus.desc",
    drops: [{ id: "dark_orb", nameKey: "darkOrb", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" }],
  },

  // ========== ICE ==========
  {
    id: "ghost",
    nameKey: "ghost",
    baseHp: 120,
    sprite: "/assets/images/enemies/Ghost.png",
    resistances: { physical: 0.8, light: -0.5, dark: 0.3 },
    isBoss: false,
    description: "monsters.ghost.desc",
    drops: [
      { id: "ectoplasm", nameKey: "ectoplasm", chance: 0.5, minCount: 1, maxCount: 2, type: "material" },
      { id: "soul_shard", nameKey: "soulShard", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
  {
    id: "vampireThrall",
    nameKey: "vampireThrall",
    baseHp: 140,
    sprite: "/assets/images/enemies/VampireThrall.png",
    resistances: { dark: 0.3, light: -0.4, physical: -0.1 },
    isBoss: false,
    description: "monsters.vampireThrall.desc",
    drops: [
      { id: "bone", nameKey: "bone", chance: 0.3, minCount: 1, maxCount: 2, type: "material" },
      { id: "ectoplasm", nameKey: "ectoplasm", chance: 0.2, minCount: 1, maxCount: 1, type: "material" },
    ],
  },
  {
    id: "ice_elemental",
    nameKey: "iceElemental",
    baseHp: 160,
    sprite: "/assets/images/enemies/IceElemental.png",
    resistances: { ice: 0.6, fire: -0.5, water: 0.2 },
    isBoss: false,
    description: "monsters.iceElemental.desc",
    drops: [
      { id: "gel", nameKey: "gel", chance: 0.4, minCount: 1, maxCount: 3, type: "material" },
      { id: "ice_crystal", nameKey: "iceCrystal", chance: 0.25, minCount: 1, maxCount: 2, type: "material" },
    ],
  },
  {
    id: "frost_wolf",
    nameKey: "frostWolf",
    baseHp: 175,
    sprite: "/assets/images/enemies/FrostWolf.png",
    resistances: { ice: 0.4, fire: -0.5, physical: 0.1 },
    isBoss: false,
    description: "monsters.frostWolf.desc",
    drops: [
      { id: "bone", nameKey: "bone", chance: 0.6, minCount: 2, maxCount: 4, type: "material" },
      { id: "demon_horn", nameKey: "demonHorn", chance: 0.15, minCount: 1, maxCount: 1, type: "material" },
      { id: "frost_fang", nameKey: "frostFang", chance: 0.2, minCount: 1, maxCount: 2, type: "material" },
    ],
  },
  {
    id: "ice_queen",
    nameKey: "iceQueen",
    baseHp: 600,
    sprite: "/assets/images/enemies/IceQueen.png",
    resistances: { ice: 0.7, fire: -0.6, water: 0.3, light: 0.2 },
    isBoss: true,
    description: "monsters.iceQueen.desc",
    drops: [
      {
        id: "hellfire_essence",
        nameKey: "hellfireEssence",
        chance: 0.002,
        minCount: 1,
        maxCount: 1,
        type: "collection",
      },
    ],
  },

  // ========== VOLCANO ==========
  {
    id: "lesserDemon",
    nameKey: "lesserDemon",
    baseHp: 315,
    sprite: "/assets/images/enemies/LesserDemon.png",
    resistances: { fire: 0.6, ice: -0.5, water: -0.3, light: 0.2 },
    isBoss: true,
    description: "monsters.lesserDemon.desc",
    drops: [
      { id: "demon_horn", nameKey: "demonHorn", chance: 0.5, minCount: 1, maxCount: 2, type: "material" },
      {
        id: "hellfire_essence",
        nameKey: "hellfireEssence",
        chance: 0.002,
        minCount: 1,
        maxCount: 1,
        type: "collection",
      },
      { id: "demon_wing", nameKey: "demonWing", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
  {
    id: "whelp",
    nameKey: "whelp",
    baseHp: 170,
    sprite: "/assets/images/enemies/Whelp.png",
    resistances: { fire: 0.5, ice: -0.4, water: -0.2 },
    isBoss: false,
    description: "monsters.whelp.desc",
    drops: [{ id: "demon_horn", nameKey: "demonHorn", chance: 0.15, minCount: 1, maxCount: 1, type: "material" }],
  },
  {
    id: "lava_slime",
    nameKey: "lavaSlime",
    baseHp: 190,
    sprite: "/assets/images/enemies/LavaSlime.png",
    resistances: { fire: 0.7, ice: -0.6, water: -0.5 },
    isBoss: false,
    description: "monsters.lavaSlime.desc",
    drops: [
      { id: "gel", nameKey: "gel", chance: 0.5, minCount: 2, maxCount: 4, type: "material" },
      {
        id: "hellfire_essence",
        nameKey: "hellfireEssence",
        chance: 0.002,
        minCount: 1,
        maxCount: 1,
        type: "collection",
      },
      { id: "lava_chunk", nameKey: "lavaChunk", chance: 0.25, minCount: 1, maxCount: 2, type: "material" },
    ],
  },
  {
    id: "fire_imp",
    nameKey: "fireImp",
    baseHp: 145,
    sprite: "/assets/images/enemies/FireImp.png",
    resistances: { fire: 0.5, ice: -0.5, light: 0.1 },
    isBoss: false,
    description: "monsters.fireImp.desc",
    drops: [
      { id: "demon_horn", nameKey: "demonHorn", chance: 0.3, minCount: 1, maxCount: 2, type: "material" },
      { id: "imp_ash", nameKey: "impAsh", chance: 0.2, minCount: 1, maxCount: 3, type: "material" },
    ],
  },
  {
    id: "inferno_dragon",
    nameKey: "infernoDragon",
    baseHp: 650,
    sprite: "/assets/images/enemies/InfernoDragon.png",
    resistances: { fire: 0.8, ice: -0.6, water: -0.5, physical: 0.3 },
    isBoss: true,
    description: "monsters.infernoDragon.desc",
    drops: [{ id: "demon_wing", nameKey: "demonWing", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" }],
  },

  // ========== CASTLE ==========
  {
    id: "skeleton",
    nameKey: "skeleton",
    baseHp: 150,
    sprite: "/assets/images/enemies/Skeleton.png",
    resistances: { light: -0.5, dark: 0.4, physical: 0.1 },
    isBoss: false,
    description: "monsters.skeleton.desc",
    drops: [
      { id: "bone", nameKey: "bone", chance: 0.7, minCount: 1, maxCount: 3, type: "material" },
      { id: "skull", nameKey: "skull", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
  {
    id: "armored_knight",
    nameKey: "armoredKnight",
    baseHp: 220,
    sprite: "/assets/images/enemies/ArmoredKnight.png",
    resistances: { physical: 0.3, light: -0.4, dark: 0.4 },
    isBoss: false,
    description: "monsters.armoredKnight.desc",
    drops: [
      { id: "bone", nameKey: "bone", chance: 0.4, minCount: 1, maxCount: 3, type: "material" },
      { id: "ancient_coin", nameKey: "ancientCoin", chance: 0.002, minCount: 1, maxCount: 3, type: "collection" },
    ],
  },
  {
    id: "cursed_banner",
    nameKey: "cursedBanner",
    baseHp: 135,
    sprite: "/assets/images/enemies/CursedBanner.png",
    resistances: { dark: 0.4, light: -0.5, physical: 0.3 },
    isBoss: false,
    description: "monsters.cursedBanner.desc",
    drops: [
      { id: "ectoplasm", nameKey: "ectoplasm", chance: 0.4, minCount: 1, maxCount: 3, type: "material" },
      { id: "soul_shard", nameKey: "soulShard", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
      { id: "cursed_cloth", nameKey: "cursedCloth", chance: 0.25, minCount: 1, maxCount: 2, type: "material" },
    ],
  },
  {
    id: "castle_lord",
    nameKey: "castleLord",
    baseHp: 700,
    sprite: "/assets/images/enemies/CastleLord.png",
    resistances: { dark: 0.5, light: -0.6, physical: 0.3, earth: 0.2 },
    isBoss: true,
    description: "monsters.castleLord.desc",
    drops: [{ id: "mage_staff", nameKey: "mageStaff", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" }],
  },

  // ========== ABYSS ==========
  {
    id: "dark_mage",
    nameKey: "darkMage",
    baseHp: 300,
    sprite: "/assets/images/enemies/DarkMage.png",
    resistances: { dark: 0.5, light: -0.5, fire: 0.2 },
    isBoss: true,
    description: "monsters.darkMage.desc",
    drops: [
      { id: "magic_scroll", nameKey: "magicScroll", chance: 0.4, minCount: 1, maxCount: 2, type: "material" },
      { id: "dark_orb", nameKey: "darkOrb", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
      { id: "mage_staff", nameKey: "mageStaff", chance: 0.002, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
  {
    id: "void_walker",
    nameKey: "voidWalker",
    baseHp: 240,
    sprite: "/assets/images/enemies/VoidWalker.png",
    resistances: { dark: 0.6, light: -0.6, physical: 0.5 },
    isBoss: false,
    description: "monsters.voidWalker.desc",
    drops: [
      { id: "ectoplasm", nameKey: "ectoplasm", chance: 0.5, minCount: 2, maxCount: 4, type: "material" },
      { id: "soul_shard", nameKey: "soulShard", chance: 0.002, minCount: 1, maxCount: 2, type: "collection" },
      { id: "void_essence", nameKey: "voidEssence", chance: 0.2, minCount: 1, maxCount: 2, type: "material" },
    ],
  },
  {
    id: "shadow_tentacle",
    nameKey: "shadowTentacle",
    baseHp: 165,
    sprite: "/assets/images/enemies/ShadowTentacle.png",
    resistances: { dark: 0.5, light: -0.5, water: 0.2, physical: 0.4 },
    isBoss: false,
    description: "monsters.shadowTentacle.desc",
    drops: [{ id: "dark_orb", nameKey: "darkOrb", chance: 0.2, minCount: 1, maxCount: 1, type: "collection" }],
  },
  {
    id: "abyss_lord",
    nameKey: "abyssLord",
    baseHp: 800,
    sprite: "/assets/images/enemies/AbyssLord.png",
    resistances: { dark: 0.8, light: -0.7, physical: 0.5 },
    isBoss: true,
    description: "monsters.abyssLord.desc",
    drops: [
      { id: "demon_wing", nameKey: "demonWing", chance: 0.002, minCount: 1, maxCount: 2, type: "collection" },
      {
        id: "hellfire_essence",
        nameKey: "hellfireEssence",
        chance: 0.002,
        minCount: 1,
        maxCount: 2,
        type: "collection",
      },
    ],
  },
];

export const LOCATION_UNLOCK_REQUIREMENTS: Partial<Record<TLocation, { prevLocation: TLocation; killLevel: number }>> =
  {
    desert: { prevLocation: "forest", killLevel: 50 },
    ice: { prevLocation: "desert", killLevel: 60 },
    volcano: { prevLocation: "ice", killLevel: 70 },
    castle: { prevLocation: "volcano", killLevel: 80 },
    abyss: { prevLocation: "castle", killLevel: 90 },
  };

export const LOCATIONS: ILocationConfig[] = [
  {
    id: "forest",
    nameKey: "forest",
    minLevel: 1,
    maxLevel: 999,
    levelScaling: 1,
    bonuses: {
      gemMultiplier: 1,
      essenceMultiplier: 1,
      expMultiplier: 1,
    },
  },
  {
    id: "desert",
    nameKey: "desert",
    minLevel: 1,
    maxLevel: 999,
    levelScaling: 2.5,
    bonuses: {
      gemMultiplier: 1.8,
      essenceMultiplier: 1.4,
      expMultiplier: 1.5,
    },
  },
  {
    id: "ice",
    nameKey: "ice",
    minLevel: 1,
    maxLevel: 999,
    levelScaling: 4,
    bonuses: {
      gemMultiplier: 2.5,
      essenceMultiplier: 1.8,
      expMultiplier: 1.8,
    },
  },
  {
    id: "volcano",
    nameKey: "volcano",
    minLevel: 1,
    maxLevel: 999,
    levelScaling: 6,
    bonuses: {
      gemMultiplier: 3.5,
      essenceMultiplier: 2.2,
      expMultiplier: 2.2,
    },
  },
  {
    id: "castle",
    nameKey: "castle",
    minLevel: 1,
    maxLevel: 999,
    levelScaling: 9,
    bonuses: {
      gemMultiplier: 4.5,
      essenceMultiplier: 2.8,
      expMultiplier: 2.8,
    },
  },
  {
    id: "abyss",
    nameKey: "abyss",
    minLevel: 1,
    maxLevel: 999,
    levelScaling: 15,
    bonuses: {
      gemMultiplier: 7,
      essenceMultiplier: 4,
      expMultiplier: 4,
    },
  },
];

export const LOCATION_ENEMIES: Record<TLocation, string[]> = {
  forest: ["slime", "goblin", "direWolf", "forest_golem", "poison_spider"],
  desert: ["mummy", "mimic", "direWolf", "sand_worm", "scarab_beetle"],
  ice: ["ghost", "direWolf", "vampireThrall", "ice_elemental", "frost_wolf"],
  volcano: ["lesserDemon", "whelp", "mimic", "lava_slime", "fire_imp"],
  castle: ["skeleton", "ghost", "mummy", "armored_knight", "cursed_banner"],
  abyss: ["lesserDemon", "vampireThrall", "void_walker", "shadow_tentacle"],
};

export const LOCATION_BOSSES: Record<TLocation, string[]> = {
  forest: ["dark_mage", "forest_guardian"],
  desert: ["lesser_demon", "desert_colossus"],
  ice: ["dark_mage", "ice_queen"],
  volcano: ["lesser_demon", "inferno_dragon"],
  castle: ["dark_mage", "castle_lord"],
  abyss: ["lesser_demon", "dark_mage", "abyss_lord"],
};

export interface ICollectionBuff {
  itemId: TInventoryItemId;
  buffType: "element_damage" | "enemy_type_damage" | "crit_power" | "click_power" | "gem_bonus" | "exp_bonus";
  target?: TElementType | string;
  value: number;
  descriptionKey: string;
}

export const COLLECTION_BUFFS: Partial<Record<TInventoryItemId, ICollectionBuff>> = {
  slime_core: {
    itemId: "slime_core",
    buffType: "enemy_type_damage",
    target: "slime",
    value: 0.5,
    descriptionKey: "buffs.slimeCore",
  },
  goblin_dagger: {
    itemId: "goblin_dagger",
    buffType: "enemy_type_damage",
    target: "goblin",
    value: 0.5,
    descriptionKey: "buffs.goblinDagger",
  },
  skull: {
    itemId: "skull",
    buffType: "enemy_type_damage",
    target: "skeleton",
    value: 0.5,
    descriptionKey: "buffs.skull",
  },
  soul_shard: {
    itemId: "soul_shard",
    buffType: "enemy_type_damage",
    target: "ghost",
    value: 0.5,
    descriptionKey: "buffs.soulShard",
  },
  dark_orb: {
    itemId: "dark_orb",
    buffType: "enemy_type_damage",
    target: "dark_mage",
    value: 0.5,
    descriptionKey: "buffs.darkOrb",
  },
  mage_staff: {
    itemId: "mage_staff",
    buffType: "element_damage",
    target: "dark",
    value: 0.2,
    descriptionKey: "buffs.mageStaff",
  },
  hellfire_essence: {
    itemId: "hellfire_essence",
    buffType: "element_damage",
    target: "water",
    value: 0.25,
    descriptionKey: "buffs.hellfireEssence",
  },
  demon_wing: {
    itemId: "demon_wing",
    buffType: "crit_power",
    value: 0.1,
    descriptionKey: "buffs.demonWing",
  },
  ancient_coin: {
    itemId: "ancient_coin",
    buffType: "gem_bonus",
    value: 0.1,
    descriptionKey: "buffs.ancientCoin",
  },
};

export const INITIAL_LOCATION_PROGRESS: TLocationProgress = {
  forest: { currentLevel: 1, maxLevelReached: 1, unlocked: true },
  desert: { currentLevel: 1, maxLevelReached: 1, unlocked: false },
  ice: { currentLevel: 1, maxLevelReached: 1, unlocked: false },
  volcano: { currentLevel: 1, maxLevelReached: 1, unlocked: false },
  castle: { currentLevel: 1, maxLevelReached: 1, unlocked: false },
  abyss: { currentLevel: 1, maxLevelReached: 1, unlocked: false },
};

export const INITIAL_GLOBAL_UPGRADES: IGlobalUpgrades = {
  clickPowerBonus: 0,
  elementDamage: {
    water: 0,
    fire: 0,
    earth: 0,
    ice: 0,
    light: 0,
    dark: 0,
    physical: 0,
  },
  collectionBuffs: {
    elementDamage: {
      water: 0,
      fire: 0,
      earth: 0,
      ice: 0,
      light: 0,
      dark: 0,
      physical: 0,
    },
    enemyTypeDamage: {},
    critPowerBonus: 0,
    gemBonus: 0,
    expBonus: 0,
  },
};
