// src/game/constant.ts
import type { LocaleKeys } from "../locales/locales";
import type { TElementType, TRarity, TWaifu, TDropItem, TConsumableItem } from "../types";

export const BASE_DROP_RATES: Record<TRarity, number> = {
  common: 0.6,
  uncommon: 0.25,
  rare: 0.1,
  epic: 0.04,
  legendary: 0.01,
  mythic: 0.001,
};

export const ELEMENT_COLORS: Record<TElementType, string> = {
  water: "#2196f3",
  fire: "#f44336",
  earth: "#4caf50",
  ice: "#00bcd4",
  light: "#ffeb3b",
  dark: "#9c27b0",
  physical: "#9e9e9e",
};

export const RARITY_COLORS: Record<TRarity, string> = {
  common: "#9e9e9e",
  uncommon: "#4caf50",
  rare: "#2196f3",
  epic: "#9c27b0",
  legendary: "#ff9800",
  mythic: "#f44336",
};

export const RARITY_KEYS: Record<TRarity, string> = {
  common: "common",
  uncommon: "uncommon",
  rare: "rare",
  epic: "epic",
  legendary: "legendary",
  mythic: "mythic",
};

export const ELEMENT_KEYS: Record<TElementType, string> = {
  water: "water",
  fire: "fire",
  earth: "earth",
  ice: "ice",
  light: "light",
  dark: "dark",
  physical: "physical",
};

export const testWaifus: TWaifu[] = [
  {
    id: "wf_tiamat_001",
    nameKey: "Tiamat",
    rarity: "mythic",
    element: "water",
    image: "/assets/images/waifus/Tiamat.png",
    description: "waifus.Tiamat.desc",
    clickPower: 1000,
    autoClick: 500,
    multiplier: 5.0,
  },
  {
    id: "wf_cerberus_001",
    nameKey: "Cerberus",
    rarity: "legendary",
    element: "dark",
    image: "/assets/images/waifus/Cerberus.png",
    description: "waifus.Cerberus.desc",
    clickPower: 800,
    autoClick: 400,
    multiplier: 4.0,
  },
  {
    id: "wf_phoenix_001",
    nameKey: "Phoenix",
    rarity: "legendary",
    element: "fire",
    image: "/assets/images/waifus/Phoenix.png",
    description: "waifus.Phoenix.desc",
    clickPower: 750,
    autoClick: 380,
    multiplier: 3.8,
  },
  {
    id: "wf_leviathan_001",
    nameKey: "Leviathan",
    rarity: "epic",
    element: "water",
    image: "/assets/images/waifus/Leviathan.png",
    description: "waifus.Leviathan.desc",
    clickPower: 500,
    autoClick: 250,
    multiplier: 3.0,
  },
  {
    id: "wf_terra_001",
    nameKey: "Terra",
    rarity: "epic",
    element: "earth",
    image: "/assets/images/waifus/Terra.png",
    description: "waifus.Terra.desc",
    clickPower: 480,
    autoClick: 240,
    multiplier: 2.9,
  },
  {
    id: "wf_yuki_001",
    nameKey: "YukiOnna",
    rarity: "epic",
    element: "ice",
    image: "/assets/images/waifus/YukiOnna.png",
    description: "waifus.YukiOnna.desc",
    clickPower: 490,
    autoClick: 245,
    multiplier: 2.95,
  },
  {
    id: "wf_ignis_001",
    nameKey: "Ignis",
    rarity: "rare",
    element: "fire",
    image: "/assets/images/waifus/Ignis.png",
    description: "waifus.Ignis.desc",
    clickPower: 300,
    autoClick: 150,
    multiplier: 2.2,
  },
  {
    id: "wf_aqua_001",
    nameKey: "Aqua",
    rarity: "rare",
    element: "water",
    image: "/assets/images/waifus/Aqua.png",
    description: "waifus.Aqua.desc",
    clickPower: 290,
    autoClick: 145,
    multiplier: 2.1,
  },
  {
    id: "wf_gaia_001",
    nameKey: "Gaia",
    rarity: "rare",
    element: "earth",
    image: "/assets/images/waifus/Gaia.png",
    description: "waifus.Gaia.desc",
    clickPower: 310,
    autoClick: 155,
    multiplier: 2.3,
  },
  {
    id: "wf_umbra_001",
    nameKey: "Umbra",
    rarity: "rare",
    element: "dark",
    image: "/assets/images/waifus/Umbra.png",
    description: "waifus.Umbra.desc",
    clickPower: 320,
    autoClick: 160,
    multiplier: 2.4,
  },
  {
    id: "wf_ruby_001",
    nameKey: "Ruby",
    rarity: "uncommon",
    element: "fire",
    image: "/assets/images/waifus/Ruby.png",
    description: "waifus.Ruby.desc",
    clickPower: 160,
    autoClick: 80,
    multiplier: 1.6,
  },
  {
    id: "wf_sapphire_001",
    nameKey: "Sapphire",
    rarity: "uncommon",
    element: "water",
    image: "/assets/images/waifus/Sapphire.png",
    description: "waifus.Sapphire.desc",
    clickPower: 150,
    autoClick: 75,
    multiplier: 1.5,
  },
  {
    id: "wf_emerald_001",
    nameKey: "Emerald",
    rarity: "uncommon",
    element: "earth",
    image: "/assets/images/waifus/Emerald.png",
    description: "waifus.Emerald.desc",
    clickPower: 165,
    autoClick: 82,
    multiplier: 1.65,
  },
  {
    id: "wf_frost_001",
    nameKey: "Frost",
    rarity: "uncommon",
    element: "ice",
    image: "/assets/images/waifus/Frost.png",
    description: "waifus.Frost.desc",
    clickPower: 155,
    autoClick: 77,
    multiplier: 1.55,
  },
  {
    id: "wf_lux_001",
    nameKey: "Lux",
    rarity: "uncommon",
    element: "light",
    image: "/assets/images/waifus/Lux.png",
    description: "waifus.Lux.desc",
    clickPower: 145,
    autoClick: 72,
    multiplier: 1.45,
  },
  {
    id: "wf_sakura_001",
    nameKey: "Sakura",
    rarity: "common",
    element: "physical",
    image: "/assets/images/waifus/Sakura.png",
    description: "waifus.Sakura.desc",
    clickPower: 100,
    autoClick: 50,
    multiplier: 1.0,
  },
  {
    id: "wf_yui_001",
    nameKey: "Yui",
    rarity: "common",
    element: "physical",
    image: "/assets/images/waifus/Yui.png",
    description: "waifus.Yui.desc",
    clickPower: 90,
    autoClick: 45,
    multiplier: 0.9,
  },
  {
    id: "wf_hana_001",
    nameKey: "Hana",
    rarity: "common",
    element: "water",
    image: "/assets/images/waifus/Hana.png",
    description: "waifus.Hana.desc",
    clickPower: 85,
    autoClick: 42,
    multiplier: 0.85,
  },
  {
    id: "wf_momo_001",
    nameKey: "Momo",
    rarity: "common",
    element: "fire",
    image: "/assets/images/waifus/Momo.png",
    description: "waifus.Momo.desc",
    clickPower: 88,
    autoClick: 44,
    multiplier: 0.88,
  },
  {
    id: "wf_rin_001",
    nameKey: "Rin",
    rarity: "common",
    element: "earth",
    image: "/assets/images/waifus/Rin.png",
    description: "waifus.Rin.desc",
    clickPower: 82,
    autoClick: 41,
    multiplier: 0.82,
  },
  {
    id: "wf_sora_001",
    nameKey: "Sora",
    rarity: "common",
    element: "physical",
    image: "/assets/images/waifus/Sora.png",
    description: "waifus.Sora.desc",
    clickPower: 86,
    autoClick: 43,
    multiplier: 0.86,
  },
];

export interface MonsterTemplate {
  id: string;
  nameKey: string;
  baseHp: number;
  hpMultiplier: number;
  sprite: string;
  resistances: Partial<Record<TElementType, number>>;
  isBoss: boolean;
  description: LocaleKeys;
  drops: TDropItem[];
}

export const MONSTER_TEMPLATES: MonsterTemplate[] = [
  {
    id: "slime",
    nameKey: "slime",
    baseHp: 100,
    hpMultiplier: 1.15,
    sprite: "/assets/images/enemies/Slime.png",
    resistances: { water: -0.3, fire: 0.2 },
    isBoss: false,
    description: "monsters.slime.desc",
    drops: [
      { id: "gel", nameKey: "gel", chance: 0.5, minCount: 1, maxCount: 3, type: "material" },
      { id: "gem", nameKey: "gem", chance: 0.3, minCount: 1, maxCount: 2, type: "currency" },
      { id: "slime_core", nameKey: "slimeCore", chance: 0.1, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
  {
    id: "goblin",
    nameKey: "goblin",
    baseHp: 120,
    hpMultiplier: 1.18,
    sprite: "/assets/images/enemies/Goblin.png",
    resistances: { physical: -0.2, fire: 0.1 },
    isBoss: false,
    description: "monsters.goblin.desc",
    drops: [
      { id: "coin", nameKey: "coin", chance: 0.6, minCount: 2, maxCount: 5, type: "currency" },
      { id: "goblin_dagger", nameKey: "goblinDagger", chance: 0.15, minCount: 1, maxCount: 1, type: "collection" },
      { id: "goblin_ear", nameKey: "goblinEar", chance: 0.4, minCount: 1, maxCount: 2, type: "material" },
    ],
  },
  {
    id: "skeleton",
    nameKey: "skeleton",
    baseHp: 150,
    hpMultiplier: 1.2,
    sprite: "/assets/images/enemies/Skeleton.png",
    resistances: { light: -0.5, dark: 0.3, physical: 0.1 },
    isBoss: false,
    description: "monsters.skeleton.desc",
    drops: [
      { id: "bone", nameKey: "bone", chance: 0.7, minCount: 1, maxCount: 3, type: "material" },
      { id: "skull", nameKey: "skull", chance: 0.2, minCount: 1, maxCount: 1, type: "collection" },
      { id: "ancient_coin", nameKey: "ancientCoin", chance: 0.25, minCount: 1, maxCount: 2, type: "currency" },
    ],
  },
  {
    id: "ghost",
    nameKey: "ghost",
    baseHp: 130,
    hpMultiplier: 1.16,
    sprite: "/assets/images/enemies/Ghost.png",
    resistances: { physical: 0.8, light: -0.4, dark: -0.2 },
    isBoss: false,
    description: "monsters.ghost.desc",
    drops: [
      { id: "ectoplasm", nameKey: "ectoplasm", chance: 0.45, minCount: 1, maxCount: 2, type: "material" },
      { id: "soul_shard", nameKey: "soulShard", chance: 0.12, minCount: 1, maxCount: 1, type: "collection" },
      { id: "essence", nameKey: "essence", chance: 0.35, minCount: 1, maxCount: 3, type: "currency" },
    ],
  },
  {
    id: "dark_mage",
    nameKey: "darkMage",
    baseHp: 500,
    hpMultiplier: 1.3,
    sprite: "/assets/images/enemies/DarkMage.png",
    resistances: { dark: -0.3, light: 0.4, fire: 0.2 },
    isBoss: true,
    description: "monsters.darkMage.desc",
    drops: [
      { id: "magic_scroll", nameKey: "magicScroll", chance: 0.4, minCount: 1, maxCount: 2, type: "material" },
      { id: "dark_orb", nameKey: "darkOrb", chance: 0.25, minCount: 1, maxCount: 1, type: "collection" },
      { id: "gem", nameKey: "gem", chance: 0.8, minCount: 5, maxCount: 10, type: "currency" },
      { id: "mage_staff", nameKey: "mageStaff", chance: 0.15, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
  {
    id: "lesser_demon",
    nameKey: "lesserDemon",
    baseHp: 600,
    hpMultiplier: 1.35,
    sprite: "/assets/images/enemies/LesserDemon.png",
    resistances: { fire: -0.4, ice: 0.3, light: 0.2 },
    isBoss: true,
    description: "monsters.lesserDemon.desc",
    drops: [
      { id: "demon_horn", nameKey: "demonHorn", chance: 0.5, minCount: 1, maxCount: 2, type: "material" },
      { id: "hellfire_essence", nameKey: "hellfireEssence", chance: 0.3, minCount: 1, maxCount: 1, type: "collection" },
      { id: "gem", nameKey: "gem", chance: 0.9, minCount: 8, maxCount: 15, type: "currency" },
      { id: "demon_wing", nameKey: "demonWing", chance: 0.2, minCount: 1, maxCount: 1, type: "collection" },
    ],
  },
];

export const CONSUMABLE_ITEMS: TConsumableItem[] = [
  {
    id: "exp_scroll_500",
    nameKey: "expScroll500",
    icon: "scroll",
    effect: { type: "exp", value: 500, target: "selected_waifu" },
    rarity: "uncommon",
  },
  {
    id: "exp_scroll_1000",
    nameKey: "expScroll1000",
    icon: "scroll",
    effect: { type: "exp", value: 1000, target: "selected_waifu" },
    rarity: "rare",
  },
  {
    id: "affection_potion",
    nameKey: "affectionPotion",
    icon: "potion",
    effect: { type: "affection", value: 10, target: "selected_waifu" },
    rarity: "common",
  },
  {
    id: "crit_boost",
    nameKey: "critBoost",
    icon: "potion_red",
    effect: { type: "crit_chance", value: 0.1, duration: 300, target: "global" },
    rarity: "rare",
  },
];
